# Generated by Django 3.0.5 on 2024-04-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240421_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='roomCharge',
        ),
    ]
