# Generated by Django 3.0.5 on 2024-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='description',
            field=models.TextField(default='', max_length=500, null=True),
        ),
    ]
