# Generated by Django 3.0.5 on 2024-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patientdischargedetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nurseId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nurseName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='assignedNurseId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='assignedNurseName',
            field=models.CharField(default='Unknown', max_length=40),
        ),
    ]
