# Generated by Django 3.0.5 on 2024-04-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patientdischargedetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
