# Generated by Django 3.0.5 on 2024-04-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_doctor_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
    ]
