# Generated by Django 3.0.5 on 2024-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_doctor_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('medication', models.CharField(max_length=40)),
                ('description', models.TextField(default='', max_length=500, null=True)),
            ],
        ),
    ]
