# Generated by Django 3.0.5 on 2024-04-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patientName',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient'),
            preserve_default=False,
        ),
    ]
