# Generated by Django 3.0.5 on 2024-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20240429_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
